theme: jekyll-theme-cayman
title: "Deeper Physical Insights through Gravitational Waves"
avatar: "YU_symbolmark.png"
title-img: "YU_symbolmark.png"
subtitle: xxth October, 2022 to xxth October, 2022
github:
  is_project_page: false
