theme: jekyll-theme-cayman
title: "Frontiers in Gravity and Fundamental Physics (YU Workshop 2022)"
avatar: "YU_symbolmark.png"
title-img: "YU_symbolmark.png"
description: xxth October, 2022 to xxth October, 2022, Yonezawa, Yamagata
github:
  is_project_page: false
